import { existsSync } from 'node:fs';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, resolve } from 'node:path';

// Private storage for evidence files. Keys are generated by the service, never taken from the user.
export interface EvidenceStorage {
  put(key: string, content: Buffer): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

// Local folder for development; production will use private object storage behind this interface (D06).
export class LocalStorage implements EvidenceStorage {
  constructor(private readonly directory: string) {}

  private path(key: string): string {
    if (!/^[0-9a-f-]{36}$/.test(key)) throw new Error('Invalid storage key');
    return join(this.directory, key);
  }

  async put(key: string, content: Buffer): Promise<void> {
    await mkdir(this.directory, { recursive: true });
    await writeFile(this.path(key), content, { flag: 'wx' });
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.path(key));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}

// EVIDENCE_DIR may be relative to the repository root (where pnpm-workspace.yaml lives).
export function resolveStorageDirectory(configured: string): string {
  if (isAbsolute(configured)) return configured;
  let dir = process.cwd();
  while (!existsSync(join(dir, 'pnpm-workspace.yaml')) && dirname(dir) !== dir) dir = dirname(dir);
  return resolve(dir, configured);
}
